description: "BETTA assistance for new teachers and students!"
email: "codefish123@gmail.com"

theme: jekyll-theme-slate

collections:
  blogposts:
    output: true

team_members:
  -
    name: "Arushi Bharadwaj"
    role: "Scrum Master"
  -
    name: "Vidhi Kulkarni"
    role: "Github Admin"
  -
    name: "Prisha Boreddy"
    role: "Technical Officer"
  - 
    name: "Saumya Palakodety"
    role: "Design"
  - 
    name: "Aryan Shah"
    role: "Deployment Manager"
